add PreloadingStrategy collection
gridsuite/filter-server pull request #100
Opened 2024-03-14 15:44 UTC by ghazwarhili

2024-03-21 15:21 UTC, anistouri approved these changes

2024-03-22 09:33 UTC, SlimaneAmar requested changes

2024-03-22 09:33 UTC, SlimaneAmar commented on src/test/java/org/gridsuite/filter/server/FilterEntityControllerTest.java
> +        given(networkStoreService.getNetwork(eq(NETWORK_UUID), nullable(PreloadingStrategy.class))).willReturn(network);
Replace `nullable` by `any`

2024-03-22 09:43 UTC, ghazwarhili commented on src/test/java/org/gridsuite/filter/server/FilterEntityControllerTest.java
> +        given(networkStoreService.getNetwork(eq(NETWORK_UUID), nullable(PreloadingStrategy.class))).willReturn(network);
done

2024-03-25 08:05 UTC, SlimaneAmar approved these changes

2024-03-25 08:26 UTC, merged