rename classes AutomaticFilter and ManualFilter
gridsuite/filter-server pull request #48
Opened 2022-11-09 17:19 UTC by Walid-Sahnoun

Signed-off-by: walid-sahnoun <walid.sahnoun@rte-france.com>

2022-11-10 11:03 UTC, FranckLecuyer requested changes

2022-11-10 11:57 UTC, Walid-Sahnoun commented on src/main/java/org/gridsuite/filter/server/dto/AbstractFilter.java
> +    @JsonSubTypes.Type(value = CriteriaFilter.class, name = "AUTOMATIC"),
ok

2022-11-10 11:57 UTC, Walid-Sahnoun commented on src/main/java/org/gridsuite/filter/server/dto/AbstractFilter.java
> +    @JsonSubTypes.Type(value = IdentifierListFilter.class, name = "MANUAL")
ok

2022-11-10 11:57 UTC, Walid-Sahnoun commented on src/main/java/org/gridsuite/filter/server/dto/IdentifierListFilter.java
>  @Schema(description = "Manual Filters", allOf = AbstractFilter.class)
yes i will do

2022-11-10 12:02 UTC, Walid-Sahnoun commented on src/main/java/org/gridsuite/filter/server/repositories/IdentifierListFilterRepository.java
> +public interface IdentifierListFilterRepository extends FilterRepository<ManualFilterEntity> {
well, in the User story only dto and jpa to change
maybe see that with the tech leads ?

2022-11-14 16:00 UTC, FranckLecuyer approved these changes

2022-11-15 09:54 UTC, archendel approved these changes

2022-11-30 17:10 UTC, dbraquart requested changes
derby.log must not be commited

2022-11-30 20:38 UTC, dbraquart approved these changes

2022-12-12 15:57 UTC, merged