[WIP] add controller to get multiple filter by id
gridsuite/filter-server pull request #53
Opened 2022-12-23 16:39 UTC by YenguiSeddik

2023-01-06 09:07 UTC, SlimaneAmar requested changes

2023-01-06 09:07 UTC, SlimaneAmar commented on src/main/resources/application-local.yaml
> +
Why these properties ?

2023-01-06 09:07 UTC, SlimaneAmar commented on src/test/java/org/gridsuite/filter/server/FilterEntityControllerTest.java
> +        var expected = "[ {\n" +
Oh !
No hardcoded json string
Rather use DTO.builder and objectMapper.writeValueAsString

2023-01-06 09:07 UTC, SlimaneAmar commented on src/test/java/org/gridsuite/filter/server/FilterEntityControllerTest.java
> +        var expected = "[ {\n" +
Same

2023-01-06 10:34 UTC, FranckLecuyer requested changes

2023-01-10 22:08 UTC, bendaamerahm commented on src/main/resources/application-local.yaml
> +
my bad i forgot to delete them

2023-01-11 16:51 UTC, bendaamerahm commented on src/main/java/org/gridsuite/filter/server/FilterController.java
> +    public ResponseEntity<List<FilterEquipments>> exportFilters(@RequestParam("ids") List<UUID> ids,
we gonna create another PR for this modification.

2023-01-13 09:32 UTC, FranckLecuyer approved these changes

2023-01-13 12:51 UTC, SlimaneAmar requested changes

2023-01-13 12:51 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/filter/server/FilterService.java
> +        if (filter.getType() == FilterType.IDENTIFIER_LIST) {
No
Add an abstract method in the `AbstractFilter` class

2023-01-19 09:46 UTC, SlimaneAmar approved these changes

2023-01-19 11:22 UTC, merged