Feat/add free properties support
gridsuite/filter-server pull request #96
Opened 2024-01-31 14:37 UTC by Meklo

2024-02-07 15:40 UTC, achour94 requested changes
The substation filter propoerties should be implemented only for the Loads

2024-02-08 13:40 UTC, Meklo commented
> The substation filter propoerties should be implemented only for the Loads

You mean free properties filter ? Substation free properties was already implemented for all equipments prior to this PR.
The reason why I've generalized the handling of free properties (only for equipments deriving of AbstractInjectionFilter) is that so it will be easier to enable for other equipments, I was discussed during the evaluation of the ticket. Implementing it only for loads would have been counter productive 
We can further disscuss it if you want

2024-02-09 09:42 UTC, achour94 approved these changes

2024-02-15 10:45 UTC, YenguiSeddik approved these changes

2024-02-15 10:49 UTC, merged